apiVersion: crd.projectcalico.org/v1
kind: HostEndpoint
metadata:
  name: master-ep
  annotations:
    argocd.argoproj.io/sync-wave: "2"  
  labels:
    role: master
spec:
  node: ubuntu22
  expectedIPs:
  - 192.168.56.110
